SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `40853_intech`.`Adresse` ADD COLUMN `Ville_idVille` INT(11) NOT NULL  AFTER `pays` , 
  ADD CONSTRAINT `fk_Adresse_Ville1`
  FOREIGN KEY (`Ville_idVille` )
  REFERENCES `40853_intech`.`Ville` (`idVille` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, DROP PRIMARY KEY 
, ADD PRIMARY KEY (`idAdresse`, `Ville_idVille`) 
, ADD INDEX `fk_Adresse_Ville1_idx` (`Ville_idVille` ASC) ;

CREATE  TABLE IF NOT EXISTS `40853_intech`.`Ville` (
  `idVille` INT NOT NULL AUTO_INCREMENT ,
  `nom` VARCHAR(45) NULL DEFAULT NULL ,
  `code` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`idVille`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;